language: objective-c
script:
  - xcodebuild -project Accessibility\ 101.xcodeproj -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -project Accessibility\ 101.xcodeproj -scheme Accessibility\ 101 -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
